// src/components/Switch/Switch.vue
<template>
  <div class="switch" @click="clickSwitch">
    <div class="buttonShow">
      <div class="pot" :style="{transform: swichState ? '' : 'translateX(-1.75em)'}"></div>
      <div class="button" :style="{transform: swichState ? '' : 'translateX(-1.75em)'}"></div>
      <div class="pot close" :style="{transform: swichState ? '' : 'translateX(-1.75em)'}"></div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps({
  swichState: {
    default: true,
    type: Boolean
  }
})
const emits = defineEmits<{
  (e: 'switch'): void
}>()
const clickSwitch = () => {
  emits('switch')
}
</script>

<style scoped lang="scss">
.switch {
  height: 1.75em;
  background-color: white;
  box-shadow: inset 1px 1px 5px #00000030;
  position: absolute;
  right: 10px;
  width: 3.45em;
  border-radius: 1em;
  display: flex;
  flex-direction: row;
  align-items: center;
  overflow: hidden;
  border: 1px solid #00000030;
  cursor: pointer;

  .buttonShow {
    display: flex;
    flex-direction: row;
    align-items: center;
    margin-left: .575em;
    justify-content: space-between;

    .pot {
      width: 8px;
      height: 8px;
      background-color: #5985eb;
      border-radius: 5px;
      transition: transform 0.3s;
      border: 1px solid #5985eb;

      &.close {
        margin-left: 0px;
        background-color: #eee;
        margin-left: .65em;
        border: 1px solid #ccc;
      }
    }

    .button {
      width: 1.55em;
      height: 1.55em;
      background-color: white;
      box-shadow: 1px 1px 3px #00000050;
      border-radius: 1em;
      border: 1px solid #00000020;
      transition: transform 0.3s;
      margin-left: .55em;
      margin-top: -.05em;
    }
  }
}
</style>

// src/components/Switch/index.tsx
const Switch: SetupFC = () => {
  const props = withDefaults(defineProps<{
    swichState: boolean
  }>(), {
    swichState: true,
  })

  const emit = defineEmits<{
    switch: []
  }>()

  return () => (
    <div
      h="1.75em" w="3.45em" right-10px rounded="1em"
      bg-white shadow-switch-in absolute
      flex items-center overflow-hidden
      border="1px solid #00000030" cursor-pointer
      onClick={() => emit('switch')}
    >
      <div
        flex items-center justify-between
        ml=".575em"
      >
        <div
          translate={props.swichState ? '' : 'x-[-1.75em]'}
          w-8px h-8px rounded-5px
          bg-primary-d border="1px solid primary-d"
          transition-transform-300
        ></div>
        <div
          translate={props.swichState ? '' : 'x-[-1.75em]'}
          w="1.55em" h="1.55em" rounded-1em
          bg-white shadow-switch-out
          border="1px solid #00000020"
          transition-transform-300
          ml=".55em" mt="-.05em"
        ></div>
        <div
          translate={props.swichState ? '' : 'x-[-1.75em]'}
          w-8px h-8px rounded-5px
          bg="#eee" border="1px solid #ccc"
          transition-transform-300 ml=".65em"
        ></div>
      </div>
    </div>
  )
}

export default Switch
