// src/windows/About.tsx
import { defineComponent } from "vue"
import { isWindow, isMac } from "../util/os"
import CloseButton from '../components/CloseButton'
import { versionText } from "../util/appVersionCode"

export default defineComponent({
  setup() {
    const os = require("os")

    const isWindows10OrAfter = isWindow() && os.release().split('.')[2] > 15063

    return () => (
      <div
        drag bg={isWindows10OrAfter ? 'transparent' : '#edd9b750'}
        flex="~ col" justify-center items-center
        w-screen h-screen
      >
        <img 
          w-130px h-130px
          mb-30px
          src="./logo.png" 
          alt="" 
        />
        <span c="#7a695c" font-bold text-24px>uyou ToDo v{versionText}</span>
        <span 
          block mt-15px 
          text-14px c="#7a695c" font-bold
        >
          Copyright (c) 2022-2023, Anthony Lu
        </span>
        {!isMac() ? <CloseButton/> : null}
      </div>
    )
  }
})

// electronWindows/about/About.tsx
import { isMac } from '../../src/util/os'
import CloseButton from '../../src/components/CloseButton'
import { versionText } from '../../src/util/appVersionCode'

const About: SetupFC = () => {
  return () => (
    <div
      drag
      bg-transparent
      flex="~ col"
      justify-center
      items-center
      w-screen
      h-screen
    >
      <img
        w-130px
        h-130px
        m="b-30px t-20px"
        src="../../logo.png"
        alt=""
      />
      <span c="#555 dark:#bbb" font-bold text-24px>
        uyou ToDo v
        {versionText}
      </span>
      <span
        block
        mt-15px
        text-14px
        c="#555 dark:#bbb"
        font-bold
      >
        Copyright (c) 2022-
        {new Date().getFullYear()}
        , Anthony Lu
      </span>
      <div
        flex
        justify-center
        items-center
        mt-35px
        text-12px
        c="#555/50 dark:#bbb/50"
        font-bold
      >
        Power By
        <div p-5px bg="#2c2e3a" rounded-full mx-7px>
          <div i-logos:electron text-3 block></div>
        </div>
        Electron v
        {/* eslint-disable-next-line node/prefer-global/process */}
        {process.versions.electron}
      </div>
      {/* eslint-disable-next-line ts/ban-ts-comment */}
      {/* @ts-expect-error */}
      {!isMac() ? <CloseButton windowName="about" /> : null}
    </div>
  )
}

export default About
