// src/components/CloseButton/index.tsx
import { useRoute } from 'vue-router'
import { closeWindow } from '../../util/windowApi'

const CloseButton: SetupFC = () => {
  const route = useRoute()

  return () => (
    <div
      fixed right-12px top-12px
      bg="black/10 hover:error-d active:error-a"
      flex items-center justify-center
      no-drag cursor-pointer c-white z-1
      w-13px h-13px p-6px rounded-full
      className="group"
      onclick={() => closeWindow(route.name as unknown as string)}
    >
      <div i-mdi:close-thick c="#555 group-hover:white group-active:white" text-13px></div>
    </div>
  )
}

export default CloseButton

// src/components/CloseButton/CLoseButton.vue
<script lang="ts" setup>
import { useRoute } from 'vue-router';

const ipcRenderer = require('electron').ipcRenderer
const route = useRoute()

const close = () => {
    ipcRenderer.send(`close-${(route.name as unknown as string)}`)
}
</script>
<template>
    <div class="close-button" @click="close">
        <span class="material-icons">close</span>
    </div>
</template>
<style lang="scss" scoped>
.close-button {
    position: fixed;
    right: 7.5px;
    top: 7.5px;
    background-color: #e5544b;
    height: 20px;
    width: 50px;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 5px;
    -webkit-app-region: no-drag;
    cursor: pointer;
    color: white;
    z-index: 1;

    &:hover {
        background-color: #c95047;
    }

    &:active {
        background-color: #99362f;
    }

    span {
        color: white;
        display: block;
        font-size: 12px;
        font-weight: bold;
        margin-left: 1px;
    }
}
</style>
